#ifndef _cairo_config_h
#define _cairo_config_h


// #define CAIRO_HAS_PNG_FUNCTIONS 1
// #define CAIRO_HAS_XLIB_SURFACE 1
// #define CAIRO_HAS_XLIB_XRENDER_SURFACE 1
// #define CAIRO_HAS_XCB_SURFACE 1
// #define CAIRO_HAS_XLIB_XCB_FUNCTIONS 1
// #define CAIRO_HAS_XCB_SHM_FUNCTIONS 1
// #define CAIRO_HAS_QT_SURFACE 1
// #define CAIRO_HAS_QUARTZ_SURFACE 1
// #define CAIRO_HAS_QUARTZ_FONT 1
// #define CAIRO_HAS_QUARTZ_IMAGE_SURFACE 1
// #define CAIRO_HAS_WIN32_SURFACE 1
// #define CAIRO_HAS_WIN32_FONT 1
// #define CAIRO_HAS_SKIA_SURFACE 1
// #define CAIRO_HAS_OS2_SURFACE 1
// #define CAIRO_HAS_BEOS_SURFACE 1
// #define CAIRO_HAS_DRM_SURFACE 1
// #define CAIRO_HAS_GALLIUM_SURFACE 1
// #define CAIRO_HAS_GL_SURFACE 1
// #define CAIRO_HAS_GLESV2_SURFACE 1
// #define CAIRO_HAS_COGL_SURFACE 1
// #define CAIRO_HAS_DIRECTFB_SURFACE 1
// #define CAIRO_HAS_VG_SURFACE 1
// #define CAIRO_HAS_EGL_FUNCTIONS 1
// #define CAIRO_HAS_GLX_FUNCTIONS 1
// #define CAIRO_HAS_WGL_FUNCTIONS 1
// #define CAIRO_HAS_SCRIPT_SURFACE 1
#define CAIRO_HAS_FT_FONT 1
// #define CAIRO_HAS_FC_FONT 1
// #define CAIRO_HAS_PS_SURFACE 1
// #define CAIRO_HAS_PDF_SURFACE 1
// #define CAIRO_HAS_SVG_SURFACE 1
// #define CAIRO_HAS_TEST_SURFACES 1
// #define CAIRO_HAS_TEE_SURFACE 1
// #define CAIRO_HAS_XML_SURFACE 1
#define CAIRO_HAS_PTHREAD 1
// #define CAIRO_HAS_GOBJECT_FUNCTIONS 1
// #define CAIRO_HAS_TRACE 1
// #define CAIRO_HAS_INTERPRETER 1
// #define CAIRO_HAS_SYMBOL_LOOKUP 1
#define CAIRO_HAS_DLSYM 1


// #define HAVE_BYTESWAP_H 1
// #define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
// #define HAVE_SYS_INT_TYPES_H 1
#define HAVE_UNISTD_H 1
// #define HAVE_UINT128_T 1
#define HAVE_UINT64_T 1


// #define HAVE_INTEL_ATOMIC_PRIMITIVES 1
// #define HAVE_LIB_ATOMIC_OPS 1
// #define HAVE_OS_ATOMIC_OPS 1

// #define HAVE_FT_LIBRARY_SETLCDFILTER 1
// #define HAVE_FT_GLYPHSLOT_EMBOLDEN 1
// #define HAVE_FT_GLYPHSLOT_OBLIQUE 1
// #define HAVE_FT_LOAD_SFNT_TABLE 1
// #define HAVE_FT_GET_X11_FONT_FORMAT 1
// #define HAVE_FT_LOAD_SFNT_TABLE 1

// #define HAVE_MEMFAULT 1
// #define HAVE_LOCKDEP 1
// #define HAVE_FCFINI 1
// #define HAVE_CTIME_R 1
// #define HAVE_CLOCK_GETTIME 1

// #define HAVE_X11_EXTENSIONS_XSHM_H 1
// #define HAVE_X11_EXTENSIONS_SHMPROTO_H 1
// #define HAVE_X11_EXTENSIONS_SHMSTR_H 1

// #define HAVE_XRENDERCREATESOLIDFILL 1
// #define HAVE_XRENDERCREATELINEARGRADIENT 1
// #define HAVE_XRENDERCREATERADIALGRADIENT 1
// #define HAVE_XRENDERCREATECONICALGRADIENT 1

// #define HAVE_VALGRIND 1


#endif